replicaCount: 2

image:
  repository: 588328284151.dkr.ecr.us-east-2.amazonaws.com/getcoins
  tag: latest

service:
  type: LoadBalancer
  port: 80
  targetPort: 5001

env:
  awsAccessKeyId: ""
  awsSecretAccessKey: ""

livenessProbe:
  path: /healthz
  port: 5001
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /ready
  port: 5001
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

imagePullSecrets:
  name: ecr-registry-secret
